modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="underground_jungle"
version="${file.jarVersion}"
displayName="Underground Jungle"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
#credits="Credits go here"
authors="HexagonNico"
#displayTest="MATCH_VERSION"

description='''
This is a description. You're welcome.
'''

[[dependencies.underground_jungle]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.underground_jungle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
