modLoader="javafml"
loaderVersion="[47,)"
license="CC BY-NC-ND 4.0"
issueTrackerURL="https://github.com/HexagonNico/UndergroundJungle/issues"

[[mods]]
modId="underground_jungle"
version="${file.jarVersion}"
displayName="Underground Jungle"
#updateJSONURL="https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/"
displayURL="https://github.com/HexagonNico/UndergroundJungle"
logoFile="logo.png"
#credits="Additional credits go here"
authors="HexagonNico"
description="Adds an underground jungle biome and an underground jungle temple"

[[dependencies.underground_jungle]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.underground_jungle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
